import {z} from 'zod';
import type {GraphMemory} from './graph-memory.js';
import type {TrustedCallContext} from './trust.js';
import type {WorkCallRuntime} from './collaboration-wait.js';
export const problemReportSchema=z.object({summary:z.string().min(1).max(1000),project:z.string().min(1).max(10000),version:z.string().min(1).max(10000),environment:z.string().min(1).max(10000),expected:z.string().min(1).max(10000),actual:z.string().min(1).max(10000),reproduction:z.array(z.string().min(1).max(4000)).min(1).max(32),evidence:z.array(z.object({label:z.string().min(1).max(256),content:z.string().min(1).max(20000),source:z.string().min(1).max(2000).optional()})).max(64),attempts:z.array(z.string().min(1).max(4000)).max(32),unknowns:z.array(z.string().min(1).max(4000)).max(32),acceptance:z.array(z.string().min(1).max(4000)).min(1).max(32)});
export const workspaceSchema=z.object({id:z.string().min(1).max(128),teamId:z.string().min(1).max(128),title:z.string().min(1).max(1000),members:z.array(z.object({principal:z.string().min(1).max(128),roles:z.array(z.enum(['reporter','worker','reviewer'])).min(1).max(3)})).min(1).max(32),expectedRevision:z.number().int().min(0),enabled:z.boolean().optional()});
export function collaborationOperations(graph:GraphMemory){return [
  {name:'work_workspace_configure',path:'/api/work/workspace/configure',description:'Operator-only explicit standing permission for a collaboration workspace. Does not grant private memory or long-term team publication. Members/roles and disabled state are enforced on every operation.',schema:workspaceSchema,run:(a:z.infer<typeof workspaceSchema>,actor?:TrustedCallContext)=>graph.collaboration.configure(a,actor)},
  {name:'work_workspaces',path:'/api/work/workspaces',description:'Discover your authenticated principal, authorized workspaces, recipient accounts, roles and the short handoff policy. No account guessing or invented grants.',schema:z.object({}),run:(_a:unknown,actor?:TrustedCallContext)=>graph.collaboration.workspaces(actor)},
  {name:'work_handoff',path:'/api/work/handoff',description:'After a user requests collaboration, atomically publish a complete problem report, task and durable recipient inbox entries. Explicit evidence content is required; local paths alone do not share files. Stable idempotencyKey; published is not recipient acceptance. maxIterations bounds an authorized code/verification loop (default 10); do not create replacement tasks to evade it.',schema:z.object({workspaceId:z.string().min(1).max(128),recipient:z.string().min(1).max(128),reviewer:z.string().min(1).max(128),report:problemReportSchema,idempotencyKey:z.string().min(1).max(256),maxIterations:z.number().int().min(1).max(100).optional()}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.handoff(a,actor)},
  {name:'work_inbox',path:'/api/work/inbox',description:'At substantive task start/reconnect discover account-bound collaboration updates. Durable seq cursor, no vector matching, no automatic read acknowledgement or model wake-up.',schema:z.object({afterSeq:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(100).optional(),unreadOnly:z.boolean().optional()}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.inbox(a,actor)},
  {name:'work_thread_get',path:'/api/work/thread',description:'Read the complete report, versions, task revision, explicit receipts and a page of discussion evidence. Follow nextCursor to read remaining events. throughSeq is safe for explicit work_ack of this page; no lease tokens are returned.',schema:z.object({taskId:z.string().min(1),afterSeq:z.number().int().min(0).optional(),limit:z.number().int().min(1).max(50).optional(),reportVersion:z.number().int().min(1).optional()}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.get(a,actor)},
  {name:'work_reply',path:'/api/work/reply',description:'Append a question, evidence, or repair explanation with eventId and expectedThreadRevision. Original reporter may also publish a full new report version. Never overwrite evidence or claim inaccessible files were checked.',schema:z.object({taskId:z.string().min(1),eventId:z.string().min(1).max(256),body:z.string().min(1).max(20000),expectedThreadRevision:z.number().int().min(1),report:problemReportSchema.optional()}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.reply(a,actor)},
  {name:'work_ack',path:'/api/work/ack',description:'Explicitly acknowledge only a delivered throughSeq actually reviewed; read is different from accepted or claimed. Acceptance is restricted to the designated recipient. Old acknowledgements do not consume later updates.',schema:z.object({taskId:z.string().min(1),throughSeq:z.number().int().min(1),kind:z.enum(['read','accepted']),eventId:z.string().min(1).max(256)}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.ack(a,actor)},
  {name:'work_iteration_submit',path:'/api/work/iteration/submit',description:'Designated worker submits one exact code version/artifact for the designated reviewer, with a live lease, task revision and stable eventId. Releases the work lease and publishes iteration_submitted. Then work_wait for the returned roundId/codeVersion; do not edit again before matching feedback.',schema:z.object({taskId:z.string().min(1),eventId:z.string().min(1).max(256),expectedRevision:z.number().int().min(1),leaseToken:z.string().min(1),codeVersion:z.string().min(1).max(256),artifactRef:z.string().min(1).max(2000),summary:z.string().min(1).max(4000),resultRefs:z.array(z.string().min(1).max(2000)).min(1).max(64)}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.submitIteration(a,actor)},
  {name:'work_verification_report',path:'/api/work/verification/report',description:'Designated reviewer reports actual verification of the current roundId/codeVersion with expectedRevision and stable eventId. passed completes; changes_requested returns work for another claim/edit; blocked requires prerequisites/user help. Evidence must contain actual text, not inaccessible paths. Old round/version results cannot advance the task.',schema:z.object({taskId:z.string().min(1),eventId:z.string().min(1).max(256),expectedRevision:z.number().int().min(1),roundId:z.string().min(1),codeVersion:z.string().min(1).max(256),verdict:z.enum(['passed','changes_requested','blocked']),summary:z.string().min(1).max(4000),evidence:problemReportSchema.shape.evidence.min(1)}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.verifyIteration(a,actor)},
  {name:'work_wait',path:'/api/work/wait',description:'Suspend this running agent until an authorized inbox update or exact iteration/verification result arrives. No LLM polling; no automatic start of an exited agent. Default 25s, maximum 55s: timeout is pending, never failure; continue with returned resume only while the user-authorized loop is active. verification_result requires taskId/roundId/codeVersion; use submission seq as afterSeq. Cancel/terminal/superseded stops the wait. No automatic read acknowledgement.',schema:z.object({taskId:z.string().min(1).optional(),afterSeq:z.number().int().min(0).optional(),until:z.enum(['inbox_update','iteration_submitted','verification_result']).optional(),roundId:z.string().min(1).optional(),codeVersion:z.string().min(1).max(256).optional(),waitMs:z.number().int().min(100).max(55000).optional()}),run:(a:any,actor?:TrustedCallContext,runtime?:WorkCallRuntime)=>graph.collaboration.wait(a,actor,runtime)},
  {name:'work_activity',path:'/api/work/activity',description:'Read authorized collaboration progress, current code iteration and active wait windows. Activity is operational status, not a receipt or memory recall. No private leases are returned.',schema:z.object({workspaceId:z.string().min(1).optional(),limit:z.number().int().min(1).max(100).optional()}),run:(a:any,actor?:TrustedCallContext)=>graph.collaboration.activity(a,actor)},
];}
