/** Export the exact runtime instructions; --check prevents documentation drift. */
import fs from 'node:fs/promises';
import { MEMORY_BOOTSTRAP } from '../src/core/bootstrap.js';
import { fileURLToPath } from 'node:url';
import { HOST_POLICY, capabilities } from '../src/core/host-contract.js';
import { memorySavePolicyPayload } from '../src/core/save-policy.js';
import { organizationPolicyPayload } from '../src/core/organization-policy.js';
import { LIFECYCLE_POLICY, LIFECYCLE_POLICY_VERSION } from '../src/core/lifecycle.js';
import { protocolRulesPayload } from '../src/core/protocol.js';

const save = memorySavePolicyPayload(), organization = organizationPolicyPayload();
const files = [
  ['memory-bootstrap-prompt.md', `# MindPond MCP startup instructions\n\n<!-- Generated by npm run docs:prompts. Edit src/core/bootstrap.ts. -->\n\n${MEMORY_BOOTSTRAP}\n`],
  ['memory-lifecycle-prompt.md', `# Host lifecycle prompt · ${LIFECYCLE_POLICY_VERSION}\n\n<!-- Generated by npm run docs:prompts. Edit src/core/lifecycle.ts. -->\n\n${LIFECYCLE_POLICY}\n`],
  ['memory-host-prompt.md', `# Host integration prompt · ${capabilities().version}\n\n<!-- Generated by npm run docs:prompts. Edit src/core/host-contract.ts. -->\n\n${HOST_POLICY}\n`],
  ['memory-save-prompt.md', `# Memory save prompt · ${save.version}\n\n<!-- Generated by npm run docs:prompts. Edit src/core/save-policy.ts. -->\n\n${save.text}\n\n## Example\n\nReplace the placeholder membership ID with one actually read.\n\n\`\`\`json\n${JSON.stringify(save.example, null, 2)}\n\`\`\`\n\n## Field limits\n\n\`\`\`json\n${JSON.stringify(save.limits, null, 2)}\n\`\`\`\n`],
  ['memory-organization-prompt.md', `# Organization prompt · ${organization.version}\n\n<!-- Generated by npm run docs:prompts. Edit src/core/organization-policy.ts. -->\n\nPass these rules WITH the immutable job snapshot returned by claim; the live claim prompt already includes both.\n\n${organization.text}\n\n## Operation contract\n\n\`\`\`json\n${JSON.stringify({ ...organization, text: undefined }, null, 2)}\n\`\`\`\n`],
  ['protocol-rules.json', `<!-- Generated by npm run docs:prompts. Edit src/core/protocol.ts. -->\n${JSON.stringify(protocolRulesPayload(), null, 2)}\n`],
];
for (const [name, content] of files) {
  const file = fileURLToPath(new URL('../docs/' + name, import.meta.url));
  if (process.argv.includes('--check')) {
    if (await fs.readFile(file, 'utf8') !== content) throw new Error(name + ' is stale; run npm run docs:prompts');
  } else await fs.writeFile(file, content);
}
console.log(process.argv.includes('--check') ? 'PASS exported host prompts match runtime rules' : 'Exported host prompts');
