import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {GraphMemory} from '../src/core/graph-memory.js';
import {getEmbeddingService} from '../src/core/embedding.js';
import {organizationMaterial} from '../src/core/organization-material.js';
import {signTeamWriteGrant} from '../src/core/domain.js';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mindpond-bridge-'));
process.env.MEMORY_DB_PATH=path.join(dir,'pond.db');process.env.EMBEDDING_ZH_ENABLED='false';
const embedding=getEmbeddingService();embedding.generateEmbedding=async()=>[];
const graph=new GraphMemory();
try {
  await graph.init();
  const save=(content:string,dimensions:Array<'lesson'|'skill'>,sessionId='s1',spaceId='project:A')=>graph.saveMemory(content,{dimensions,sessionId,memberships:[{spaceId,memoryType:dimensions[0]}]});
  const a=await save('Failed release requires a verified recovery path.',['lesson']);
  const b=await save('Preserve edits before recovering the verified release.',['lesson','skill']);
  const c=await save('Recovery procedure: retain patch, restore validated release, run health check.',['skill']);
  const outsider=await save('This belongs to a different session.',['skill'],'s2');
  const far=await save('Different project context.',['skill'],'s1','project:B');
  await graph.addMembership(b.id,'project:B','skill');
  const bm=b.memberships.find(m=>m.memoryType==='lesson')!,bs=b.memberships.find(m=>m.memoryType==='skill')!;
  await graph.upsertAssociation(a.memberships[0].id,bm.id,'project:A','lesson',.9);
  await graph.upsertAssociation(bs.id,c.memberships[0].id,'project:A','skill',.9);
  await assert.rejects(graph.upsertAssociation(bs.id,outsider.memberships[0].id,'project:A','skill',.9),/domains/);
  const bOther=(await graph.getMemberships(b.id)).find(m=>m.spaceId==='project:B')!;
  await graph.upsertAssociation(bOther.id,far.memberships[0].id,'project:B','skill',.9);
  const query={nodeId:a.id,sessionId:'s1',maxDepth:3,minScore:.1};
  const hits=await graph.search(query);const hit=hits.find(h=>h.node.id===c.id)!;
  assert(hit);assert.equal(hit.depth,2);assert(Math.abs(hit.score-.81)<1e-9);
  assert.deepEqual(hit.path,[a.id,b.id,c.id]);assert.equal(hit.associationPath?.length,2);
  assert.deepEqual(hit.dimensionBridges,[{memoryId:b.id,spaceId:'project:A',from:'lesson',to:'skill'}]);
  assert(!hits.some(h=>h.node.id===outsider.id || h.node.id===far.id));
  assert(!(await graph.search({...query,maxDepth:1})).some(h=>h.node.id===c.id));
  const before=await graph.getNodeById(b.id,{trackAccess:false});
  await graph.editMemory(b.id,{dimensions:['lesson'],expectedUpdatedAt:before!.updatedAt});
  assert(!(await graph.search(query)).some(h=>h.node.id===c.id));
  const changed=await graph.getNodeById(b.id,{trackAccess:false});
  await graph.editMemory(b.id,{dimensions:['lesson','skill'],expectedUpdatedAt:changed!.updatedAt});
  assert((await graph.search(query)).some(h=>h.node.id===c.id),'readding an identity must reactivate its placement');
  const single=await save('Single identity can be reclassified.',['lesson'],'s1','reclassify');
  const version=await graph.getNodeById(single.id,{trackAccess:false});
  await graph.editMemory(single.id,{dimensions:['skill'],expectedUpdatedAt:version!.updatedAt});
  assert.deepEqual((await graph.getMemberships(single.id,{activeOnly:true})).map(m=>m.memoryType),['skill']);
  await assert.rejects(save('Invalid identity',['event'] as any),/dimensions/);
  console.log('PASS explicit multi-dimension bridge, two-hop product, complete path, session/project isolation, depth budget and identity removal');
  process.env.MEMORY_TEAM_AUTH_SECRET='isolated-test-secret';
  const now=Date.now(),team={kind:'team' as const,id:'T'};
  const grant=signTeamWriteGrant({v:1,authorizationId:'test',teamId:'T',requestId:'user-request',operations:['save'],issuedAt:now,expiresAt:now+60_000},process.env.MEMORY_TEAM_AUTH_SECRET);
  const shared=await graph.saveMemory('Approved shared recovery procedure.',{dimensions:['skill'],domain:team,teamAuthorization:grant,memberships:[{spaceId:'project:A',memoryType:'skill'}]});
  const own={kind:'personal' as const,id:'default'},other={kind:'personal' as const,id:'other'};
  const private1=await graph.saveMemory('Private procedure A.',{dimensions:['skill'],domain:own,memberships:[{spaceId:'project:A',memoryType:'skill'}]});
  const private2=await graph.saveMemory('Private procedure B.',{dimensions:['skill'],domain:other,memberships:[{spaceId:'project:A',memoryType:'skill'}]});
  const basis={reason:'Use the approved recovery procedure for this private task.',context:'Project A recovery; no sharing of private source.'};
  await assert.rejects(graph.linkTeamReference(private1.memberships[0].id,shared.memberships[0].id,basis,.8,{domains:[own]}));
  await graph.linkTeamReference(private1.memberships[0].id,shared.memberships[0].id,basis,.8,{domains:[own,team]});
  await graph.linkTeamReference(private2.memberships[0].id,shared.memberships[0].id,basis,.8,{domains:[other,team]});
  const crossing=await graph.search({nodeId:private1.id,domains:[own,other,team],maxDepth:5});
  assert.equal(crossing.find(h=>h.node.id===shared.id)?.score,.8);assert(!crossing.some(h=>h.node.id===private2.id));
  assert.equal(crossing.find(h=>h.node.id===shared.id)?.associationPath?.[0].evidence?.[0].reason,basis.reason);
  assert.deepEqual((await graph.search({nodeId:shared.id,domains:[own,other,team]})).map(h=>h.node.id),[shared.id]);
  assert(!(await graph.search({nodeId:private1.id,domains:[own]})).some(h=>h.node.id===shared.id));
  const privateVersion=await graph.getNodeById(private1.id,{trackAccess:false});
  await graph.editMemory(private1.id,{content:'Changed private procedure A.',expectedUpdatedAt:privateVersion!.updatedAt});
  assert.equal((await graph.search({nodeId:private1.id,domains:[own,team]})).find(h=>h.node.id===shared.id)?.associationPath?.[0].evidenceStatus,'needs_review');
  assert(!(await graph.graphNeighborhood(private1.id,{domains:[own]})).nodes.some(n=>n.id===shared.id));
  console.log('PASS private team references require readable team scope, carry basis, never backflow or change team knowledge');
  const event=await graph.createNode({dimension:'event',layer:'L0',sessionId:'s1',content:'Observed failure log.'});
  await (graph as any).db.run("INSERT INTO edges(id,from_id,to_id,label,weight,created_at) VALUES('source-test',?,?,'derived_from',1,?)",[a.id,event.id,Date.now()]);
  const trace=await graph.traceMemory(a.id,{sessionId:'s1'});assert(trace.nodes.some(n=>n.id===event.id));
  assert(!(await graph.search({...query,includeEvents:true,includeL0:true})).some(h=>h.node.id===event.id));
  const view=await graph.getFullGraph(100);assert(view.edges.every(e=>e.kind==='semantic'));assert(!view.nodes.some(n=>n.id===event.id));
  assert((await graph.graphNeighborhood(a.id,{sessionId:'s1'})).edges.some(e=>e.kind==='provenance'));
  console.log('PASS graph uses semantic edges; logs expand through explicit provenance trace, not ordinary ripple');
  assert.equal((await graph.listNodes({dimension:'event',sessionId:'s1'})).total,1);
  assert((await graph.listNodes({dimension:'skill',operatorAll:true})).nodes.every(n=>n.dimensions?.includes('skill')));
  assert((await graph.getStats()).byDimension.skill>=3);
  const first=await save('Recovery keeps the patch. Never reset an unverified database.',['lesson','skill'],'s1','organize');
  const second=await save('Retain the patch before recovery. Never reset an unverified database.',['lesson','skill'],'s1','organize');
  const ids=[first,second].map(s=>s.memberships.find(m=>m.memoryType==='lesson')!.id);
  const job=await graph.claimOrganizationJob({spaceId:'organize',memoryType:'lesson',domain:{kind:'session',id:'s1'},membershipIds:ids});
  assert(job);
  const packed=organizationMaterial(job);
  assert.equal(Object.keys(packed.memories).length,2);
  assert.equal((packed.memories[first.id] as any).content,'Recovery keeps the patch. Never reset an unverified database.');
  const organized=await graph.commitOrganizationPlan(job.id,{operations:[{kind:'consolidate',membershipIds:ids,content:'Retain the patch before recovery. Never reset an unverified database.',dimensions:['lesson','skill'],reason:'Same complete procedure, preserving the prohibition.'}]});
  assert.deepEqual((await graph.getMemberships(organized.createdMemoryIds[0],{activeOnly:true})).map(m=>m.memoryType).sort(),['lesson','skill']);
  await graph.close();await graph.init();
  assert.deepEqual((await graph.getNodeById(organized.createdMemoryIds[0],{trackAccess:false}))!.dimensions,['lesson','skill']);
  assert.equal((await (graph as any).db.all('PRAGMA foreign_key_check')).length,0);
  console.log('PASS dimension filters/statistics, lossless organization material, consolidated bridge memberships and restart persistence');
} finally {await graph.close();await fs.rm(dir,{recursive:true,force:true});}
