/** Deterministic contracts: real temporary SQLite + controlled vector channels. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { GraphMemory } from '../src/core/graph-memory.js';
import { getEmbeddingService } from '../src/core/embedding.js';
import { getZhEmbeddingService } from '../src/core/embedding-zh.js';

const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mindpond-anchors-'));
process.env.MEMORY_DB_PATH=path.join(dir,'pond.db');
process.env.EMBEDDING_ZH_ENABLED='true';
const main=getEmbeddingService(),zh=getZhEmbeddingService();
const originalMain=main.generateEmbedding,originalZh=zh.generateEmbedding;
let offline=false;
main.generateEmbedding=async text=>!offline && /guarded restart|revive daemon/.test(text) ? [1,...Array(383).fill(0)] : [];
zh.generateEmbedding=async text=>!offline && /中文召回|设备复原/.test(text) ? [1,...Array(511).fill(0)] : [];
const g=new GraphMemory();
let reader:GraphMemory|undefined;
let checks=0;
function pass(name:string){checks++;console.log('PASS '+name);}
const scope={spaceId:'project:A',memoryType:'recovery'};
const other={spaceId:'project:B',memoryType:'recovery'};
const body='An independent watchdog keeps validated releases and preserves rejected edits.';
const anchor={text:'guarded restart recovery',basis:'validated releases',...scope};
try {
  await g.init();
  const options={memberships:[scope,other],anchors:[anchor],idempotencyKey:'first'};
  const saved=await g.saveMemory(body,options);
  assert.equal((await g.getNodeById(saved.id,{trackAccess:false}))?.anchors?.length,1);
  assert.equal((await g.saveMemory(body,options)).id,saved.id);
  await assert.rejects(g.saveMemory(body,{...options,anchors:[]}),/idempotency_conflict/);
  pass('save/get and idempotent replay preserve anchors; altered anchors conflict');
  const count=(await g.getStats()).total;
  for(const anchors of [Array(7).fill(anchor),[anchor,anchor],[{...anchor,basis:'invented evidence'}],[{...anchor,spaceId:'outside'}],[{...anchor,text:''}]]) {
    await assert.rejects(g.saveMemory(body,{memberships:[scope],anchors}));
  }
  assert.equal((await g.getStats()).total,count);
  pass('invalid limits, duplicate entrances, unsupported basis and scope reject before writes');
  const noAnchors=await g.search({query:'revive daemon',useAnchors:false,maxDepth:0});
  assert(!noAnchors.some(h=>h.node.id===saved.id));
  const hits=await g.search({query:'revive daemon',maxDepth:0});
  const seed=hits.find(h=>h.node.id===saved.id)!;
  assert(seed);assert.equal(seed.depth,0);assert.equal(seed.spaceId,scope.spaceId);
  assert.equal(seed.matchedAnchors?.[0].channel,'anchor-vector');assert.equal(seed.node.content,body);
  pass('paraphrase vector hit returns one complete canonical body with entrance evidence');
  const b=await g.saveMemory('Boreal lantern custody',{memberships:[scope]});
  const c=await g.saveMemory('Cobalt winter ledger',{memberships:[scope]});
  const wrong=await g.saveMemory('Obsidian orchard record',{memberships:[other]});
  const aA=saved.memberships.find(m=>m.spaceId===scope.spaceId)!;
  const aB=saved.memberships.find(m=>m.spaceId===other.spaceId)!;
  await g.upsertAssociation(aA.id,b.memberships[0].id,scope.spaceId,scope.memoryType,.9);
  await g.upsertAssociation(b.memberships[0].id,c.memberships[0].id,scope.spaceId,scope.memoryType,.9);
  await g.upsertAssociation(aB.id,wrong.memberships[0].id,other.spaceId,other.memoryType,.9);
  const ripple=await g.search({query:'revive daemon',maxDepth:2});
  assert(ripple.some(h=>h.node.id===b.id));assert(!ripple.some(h=>h.node.id===wrong.id));
  assert(Math.abs(ripple.find(h=>h.node.id===c.id)!.score-seed.score*.81)<1e-9);
  assert.equal(ripple.find(h=>h.node.id===c.id)!.matchedAnchors?.[0].id,seed.matchedAnchors?.[0].id);
  assert(!(await g.search({query:'revive daemon',spaceId:other.spaceId})).some(h=>h.node.id===saved.id));
  pass('scoped anchor activates only its own placement; two ripple hops remain 0.9 × 0.9');
  const old=await g.getNodeById(saved.id,{trackAccess:false});
  const six=Array.from({length:6},(_,i)=>({...anchor,text:anchor.text+' situation '+i}));
  await g.editMemory(saved.id,{anchors:six,expectedUpdatedAt:old!.updatedAt});
  const sixHits=await g.search({query:'revive daemon',maxDepth:0});
  assert.equal(sixHits.filter(h=>h.node.id===saved.id).length,1);
  assert.equal(sixHits.find(h=>h.node.id===saved.id)!.score,seed.score);
  pass('six matching anchors neither duplicate a node nor sum its strength');
  reader=new GraphMemory();await reader.init();
  assert((await reader.search({query:'revive daemon'})).some(h=>h.node.id===saved.id));
  await g.editMemory(saved.id,{content:body+' New limits apply.'});
  assert((await g.getNodeById(saved.id,{trackAccess:false}))!.anchors!.every(a=>a.status==='needs_review'));
  assert(!(await reader.search({query:'revive daemon'})).some(h=>h.node.id===saved.id));
  await assert.rejects(g.editMemory(saved.id,{anchors:[anchor]}),/expectedUpdatedAt/);
  await assert.rejects(g.editMemory(saved.id,{anchors:[anchor],expectedUpdatedAt:old!.updatedAt}),/stale_snapshot/);
  pass('body edits invalidate anchors across readers; missing/stale edit versions are rejected');
  const job=await g.claimOrganizationJob({...scope,maxMembers:8});assert(job);
  await g.commitOrganizationPlan(job.id,{operations:[{kind:'reanchor',membershipIds:[aA.id],anchors:[anchor],reason:'Rechecked the complete body and preserved scope.'}]});
  assert((await reader.search({query:'revive daemon'})).some(h=>h.node.id===saved.id));
  pass('organization reanchor restores reviewed entrances without rewriting the body');
  const current=await g.getNodeById(saved.id,{trackAccess:false});
  await g.editMemory(saved.id,{anchors:[anchor,{...anchor,...other}],expectedUpdatedAt:current!.updatedAt});
  const scopedJob=await g.claimOrganizationJob({...scope,membershipIds:[aA.id]});assert(scopedJob);
  await assert.rejects(g.commitOrganizationPlan(scopedJob.id,{operations:[{
    kind:'reanchor',membershipIds:[aA.id],anchors:six,reason:'Too many when the other placement is counted.',
  }]}),/memory-wide limit/);
  await g.commitOrganizationPlan(scopedJob.id,{operations:[{kind:'reanchor',membershipIds:[aA.id],anchors:[],reason:'Remove only this placement.'}]});
  const retained=(await g.getNodeById(saved.id,{trackAccess:false}))!.anchors!;
  assert.equal(retained.length,1);assert.equal(retained[0].spaceId,other.spaceId);
  const reviewed=await g.getNodeById(saved.id,{trackAccess:false});
  await g.editMemory(saved.id,{anchors:[anchor],expectedUpdatedAt:reviewed!.updatedAt});
  pass('single-member review preserves other placements and enforces the memory-wide six-anchor budget');
  offline=true;
  assert((await reader.search({query:anchor.text})).some(h=>h.node.id===saved.id && h.matchedAnchors?.some(a=>a.channel==='anchor-text')));
  offline=false;
  pass('text anchor search works while both embedding models are unavailable');
  const zhSaved=await g.saveMemory('硬件备用电源在测试环境中已验证。',{memberships:[scope],anchors:[{text:'设备复原流程',basis:'备用电源',...scope}]});
  assert((await g.search({query:'中文召回入口'})).some(h=>h.node.id===zhSaved.id && h.matchedAnchors?.some(a=>a.channel==='anchor-zh')));
  pass('Chinese vector channel independently retrieves anchors');
  const sql=(g as any).db, store=(g as any).anchors;
  const validMain=Buffer.from(new Float32Array([1,...Array(383).fill(0)]).buffer);
  await sql.run('UPDATE memory_anchors SET embedding=?,zh_embedding=NULL WHERE memory_id=?',[validMain,zhSaved.id]);
  await store.backfill();
  const recovered=await sql.get('SELECT embedding,zh_embedding FROM memory_anchors WHERE memory_id=?',[zhSaved.id]);
  assert.deepEqual(recovered.embedding,validMain);
  assert.equal(recovered.zh_embedding.length,512*4);
  assert((await reader.search({query:'中文召回入口'})).some(h=>h.node.id===zhSaved.id));
  const mixed=await g.saveMemory(body,{memberships:[scope],anchors:[{...anchor,text:'guarded restart with one 字'}]});
  assert.equal((await sql.get('SELECT zh_model FROM memory_anchors WHERE memory_id=?',[mixed.id])).zh_model,'not-applicable');
  // Simulate an older row: classify once, then it must stop requesting ZH vectors.
  await sql.run('UPDATE memory_anchors SET zh_model=NULL WHERE memory_id=?',[mixed.id]);
  await store.backfill();
  assert.equal((await sql.get('SELECT zh_model FROM memory_anchors WHERE memory_id=?',[mixed.id])).zh_model,'not-applicable');
  pass('background repair preserves valid channels, refreshes readers, and skips non-Chinese ZH work');
  const session=await g.saveMemory(body,{sessionId:'private-session',domain:{kind:'session',id:'private-session'},memberships:[scope],anchors:[anchor]});
  assert(!(await g.search({query:'revive daemon'})).some(h=>h.node.id===session.id));
  assert((await g.search({query:'revive daemon',sessionId:'private-session'})).some(h=>h.node.id===session.id));
  await assert.rejects(g.search({query:'revive daemon',sessionId:'another',domains:[{kind:'session',id:'private-session'}]}));
  pass('session anchors obey current-session visibility and cannot widen a read');
  await g.setSessionState('private-session','closed');
  assert(!(await reader.search({query:'revive daemon',sessionId:'private-session'})).some(h=>h.node.id===session.id));
  await g.purgeClosedSession('private-session');
  assert.equal((await store.list(session.id)).length,0);
  pass('closed sessions disappear even from warm readers; purge removes their anchor payloads');
  const receipt=await g.recall({query:'revive daemon',maxDepth:0,hostId:'test',runId:'run'});
  await g.reportRecallFeedback({recallId:receipt.recallId,hostId:'test',runId:'run',decisions:[{memoryId:saved.id,disposition:'rejected',reason:'Current environment does not satisfy the documented conditions.'}]});
  pass('anchor retrieval participates in the existing host adoption feedback contract');
  await g.deleteNode(saved.id);
  assert(!(await reader.search({query:'revive daemon'})).some(h=>h.node.id===saved.id));
  assert.equal((await (g as any).anchors.list(saved.id)).length,0);
  pass('canonical deletion cascades to anchors and is visible to another reader');
  console.log('PASS '+checks+' anchor contract groups; vectors are deterministic fixtures, not a real-model quality claim');
} finally {
  await reader?.close();await g.close();main.generateEmbedding=originalMain;zh.generateEmbedding=originalZh;
  await fs.rm(dir,{recursive:true,force:true});
}
