import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { GraphMemory } from '../src/core/graph-memory.js';
import { organizationTask } from '../src/core/organization-policy.js';
import { MEMORY_SAVE_POLICY } from '../src/core/save-policy.js';

const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'mindpond-context-'));
process.env.MEMORY_DB_PATH = path.join(dir, 'pond.db');
process.env.EMBEDDING_ZH_ENABLED = 'false';
let g = new GraphMemory();
try {
  await g.init();
  const spaceId = '项目 P', memoryType = '配置';
  const make = (content: string) => g.createNode({ dimension: 'fact', content, memberships: [{ spaceId, memoryType }], embedding: [1, ...Array(383).fill(0)] });
  const a = await make('项目 P 本地服务监听 7903 端口。'), b = await make('远程访问本地服务必须经过代理。'), c = await make('修改本地端口后也需要修改代理目标。');
  const ma = (await g.getMemberships(a.id))[0], mb = (await g.getMemberships(b.id))[0], mc = (await g.getMemberships(c.id))[0];
  const basis = { reason: '代理仍指向旧端口曾导致远程调试失败，需要一起核对', context: '项目 P 本地调试，更改端口后；不适用于生产环境' };
  assert(MEMORY_SAVE_POLICY.includes('EVERY related[]'));
  await assert.rejects(g.saveMemory('无依据不能写入', { related: [{ memoryId: a.id, score: .9 } as any] }), /reason and context/);
  assert.equal((await g.listNodes({})).total, 3);
  let link = await g.upsertAssociation(ma.id, mc.id, spaceId, memoryType, .9, basis);
  assert.equal(link.evidenceStatus, 'supported');
  await g.upsertAssociation(mc.id, ma.id, spaceId, memoryType, .9, basis);
  link = (await g.listAssociations(a.id))[0]; assert.equal(link.evidence!.length, 1); assert.equal(link.weight, .9);
  await g.upsertAssociation(ma.id, mc.id, spaceId, memoryType, .9, { reason: '本地测试复现端口冲突时也需要检查代理目标', context: '项目 P 的本地回归测试' });
  link = (await g.listAssociations(a.id))[0]; assert.equal(link.evidence!.length, 2);
  const reverse = await g.search({ nodeId: c.id, maxDepth: 1, spaceId, memoryType });
  assert.equal(reverse.find(r => r.node.id === a.id)!.associationPath![0].evidence!.length, 2);
  const opts = { spaceId, memoryType, membershipIds: [ma.id, mb.id] };
  const job = await g.claimOrganizationJob(opts); assert(job);
  assert(organizationTask(job).prompt!.includes(basis.context));
  await g.upsertAssociation(ma.id, mc.id, spaceId, memoryType, .8, basis);
  await assert.rejects(g.commitOrganizationPlan(job.id, { operations: [{ kind: 'keep', membershipIds: [ma.id] }] }), /associations changed/);
  await g.releaseOrganizationJob(job.id);
  await g.updateNodeContent(a.id, a.content + ' 仅绑定本机回环地址。');
  assert.equal((await g.listAssociations(a.id))[0].evidenceStatus, 'needs_review');
  const fresh = await g.claimOrganizationJob(opts); assert(fresh);
  await assert.rejects(g.validateOrganizationPlan(fresh.id, { operations: [{ kind: 'associate', membershipIds: [ma.id, mb.id], weight: .9 } as any] }), /reason and context/);
  const plan = { operations: [{ kind: 'consolidate' as const, membershipIds: [ma.id, mb.id], content: '项目 P 本地服务监听本机回环地址的 7903 端口；远程访问必须经过代理。' }] };
  const receipt = await g.commitOrganizationPlan(fresh.id, plan);
  const replacement = receipt.createdMemoryIds[0];
  let carried = (await g.listAssociations(replacement))[0];
  assert.equal(carried.weight, .8); assert.equal(carried.evidence!.length, 2); assert.equal(carried.evidenceStatus, 'needs_review');
  assert(carried.evidence!.some(e => e.context === basis.context));
  assert.equal((await g.listAssociations(c.id)).length, 1);
  assert.deepEqual(await g.commitOrganizationPlan(fresh.id, plan), receipt);
  await g.close(); g = new GraphMemory(); await g.init();
  carried = (await g.listAssociations(replacement))[0]; assert.equal(carried.evidence!.length, 2); assert.equal(carried.evidenceStatus, 'needs_review');
  for (const e of carried.evidence!) await g.reviewAssociationEvidence(carried.id, e.id, 'confirm', '核对整合正文仍保留本地调试和代理访问条件');
  assert.equal((await g.listAssociations(replacement))[0].evidenceStatus, 'supported');
  await assert.rejects(g.reviewAssociationEvidence(carried.id, carried.evidence![0].id, 'retire', '旧页面提交', carried.updatedAt), /stale_snapshot/);
  for (const e of carried.evidence!) await g.reviewAssociationEvidence(carried.id, e.id, 'retire', '测试：已确认此代理方案整体停用');
  assert.equal((await g.listAssociations(replacement))[0].evidenceStatus, 'retired');
  assert(!(await g.search({ nodeId: c.id, maxDepth: 2, spaceId, memoryType })).some(r => r.node.id === replacement));
  await g.reviewAssociationEvidence(carried.id, carried.evidence![0].id, 'confirm', '测试：代理方案恢复，原条件仍成立');
  assert((await g.search({ nodeId: c.id, maxDepth: 2, spaceId, memoryType })).some(r => r.node.id === replacement));
  const legacy = await g.upsertAssociation((await g.getMemberships(replacement))[0].id, (await g.addMembership(b.id, spaceId, '历史')).id, spaceId, memoryType, .5).catch(() => null);
  assert.equal(legacy, null, 'context never relaxes type boundaries');
  const d = await make('独立历史记录'), md = (await g.getMemberships(d.id))[0];
  assert.equal((await g.upsertAssociation(mc.id, md.id, spaceId, memoryType, .4)).evidenceStatus, 'missing');
  const logs = await g.actionLogPage({ action: 'association_carried' }); assert(logs.log.some(l => l.reason.includes(basis.context)));
  console.log('PASS contextual basis required, multiple contexts retained, duplicate evidence idempotent');
  console.log('PASS reverse ripple explains original context, immutable snapshots detect association changes');
  console.log('PASS edits mark evidence for review; consolidation carries external evidence across restart');
  console.log('PASS legacy evidence remains explicitly missing; space/type boundary and audit preserved');
  console.log('PASS evidence review converges after consolidation; retire/restore changes ripple with stale-write protection');
} finally { await g.close(); await fs.rm(dir, { recursive: true, force: true }); }
