import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { GraphMemory } from '../src/core/graph-memory.js';
import { organizationTask } from '../src/core/organization-policy.js';

const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'mindpond-workbench-'));
process.env.MEMORY_DB_PATH = path.join(dir, 'test.db');
process.env.EMBEDDING_ZH_ENABLED = 'false';
let graph = new GraphMemory();
const checks: string[] = [];
try {
  await graph.init();
  const make = (content: string, spaceId = '项目 P', memoryType = '配置') => graph.createNode({
    dimension: 'fact', content, memberships: [{ spaceId, memoryType }], embedding: [1, ...Array(383).fill(0)] });
  const a = await make('项目 P 本地调试服务使用 7903 端口。');
  const b = await make('项目 P 本地服务仅绑定 127.0.0.1，远程访问经代理转发。');
  const c = await make('部署服务前需要验证环境变量和代理配置。');
  await graph.addMembership(a.id, '共享文档', '知识');
  const ma = (await graph.getMemberships(a.id))[0], mb = (await graph.getMemberships(b.id))[0], mc = (await graph.getMemberships(c.id))[0];
  await graph.upsertAssociation(ma.id, mc.id, '项目 P', '配置', .8);
  const opts = { spaceId: '项目 P', memoryType: '配置', membershipIds: [ma.id, mb.id] };
  const task = await graph.claimOrganizationJob(opts); assert(task);
  assert(organizationTask(task).prompt?.includes('membership.id'));
  await assert.rejects(graph.claimOrganizationJob(opts), /leased/);
  checks.push('selected sources are leased exclusively; host receives a complete prompt');
  const plan = { operations: [{ kind: 'consolidate' as const, membershipIds: [ma.id, mb.id], content: '项目 P 本地调试服务使用 7903 端口，仅绑定 127.0.0.1；远程访问经代理转发。', reason: '端口、监听地址与代理条件均已保留。' }] };
  const preview = await graph.validateOrganizationPlan(task.id, plan);
  assert.equal(preview.removedAssociations.length, 1);
  assert((await graph.getMemberships(a.id))[0].active);
  await assert.rejects(graph.commitOrganizationPlan(task.id, { operations: [{ kind: 'unknown', membershipIds: [ma.id] }] } as any), /Invalid/);
  await assert.rejects(graph.commitOrganizationPlan(task.id, { operations: Array.from({ length: 49 }, () => ({ kind: 'keep' as const, membershipIds: [ma.id] })) }), /0–48/);
  await assert.rejects(graph.commitOrganizationPlan(task.id, { operations: [plan.operations[0], plan.operations[0]] }), /twice/);
  checks.push('preview is read-only; malformed, oversized and overlapping plans rejected; an empty plan is a legal no_change');
  await graph.updateNodeContent(a.id, '项目 P 本地调试服务改用 7904 端口。');
  await assert.rejects(graph.commitOrganizationPlan(task.id, plan), /stale_snapshot/);
  assert.equal((await graph.getOrganizationJob(task.id))!.members.find(m => m.memory.id === a.id)!.memory.content, a.content);
  checks.push('body edits invalidate immutable snapshots');
  await graph.releaseOrganizationJob(task.id);
  const fresh = await graph.claimOrganizationJob(opts); assert(fresh);
  plan.operations[0].content = '项目 P 本地调试服务使用 7904 端口，仅绑定 127.0.0.1；远程访问经代理转发。';
  const receipt = await graph.commitOrganizationPlan(fresh.id, plan);
  assert.deepEqual(await graph.commitOrganizationPlan(fresh.id, plan), receipt);
  assert.equal((await graph.getMemberships(a.id)).find(m => m.spaceId === '共享文档')?.active, true);
  assert.equal((await graph.getMemberships(a.id)).find(m => m.spaceId === '项目 P')?.active, false);
  assert.equal((await graph.listAssociations(a.id)).length, 0);
  assert((await graph.getNodeById(a.id, { trackAccess: false }))?.content.includes('7904'));
  const log = await graph.actionLogPage({ action: 'organization_consolidate' });
  assert(log.log.some(e => e.reason.includes(fresh.id)));
  checks.push('atomic replacement preserves other spaces and sources; retries return same receipt; removal audited');
  await graph.close(); graph = new GraphMemory(); await graph.init();
  assert.deepEqual(await graph.commitOrganizationPlan(fresh.id, plan), receipt);
  assert.equal((await graph.getMemberships(a.id)).length, 2, 'restart must not invent legacy membership');
  assert.equal((await graph.getMemberships(receipt.createdMemoryIds[0])).length, 1);
  const retained = await graph.listNodes({ spaceId: '项目 P', memoryType: '配置', activeOnly: true });
  assert(!retained.nodes.some(n => n.id === a.id || n.id === b.id));
  checks.push('restart preserves idempotency and space membership boundaries');
  const d = await make('归档记录也需要完整的适用条件。');
  const md = (await graph.getMemberships(d.id))[0];
  const renewal = await graph.claimOrganizationJob({ ...opts, membershipIds: [mc.id, md.id] }); assert(renewal);
  assert(await graph.renewOrganizationJob(renewal.id) > Date.now());
  await graph.releaseOrganizationJob(renewal.id);
  await assert.rejects(graph.commitOrganizationPlan(renewal.id, { operations: [{ kind: 'keep', membershipIds: [mc.id] }] }), /expired/);
  const edited = await graph.getNodeById(c.id, { trackAccess: false }); assert(edited);
  await graph.editMemory(c.id, { content: edited.content + ' 完成后记录实际结果。', expectedUpdatedAt: edited.updatedAt });
  await assert.rejects(graph.editMemory(c.id, { content: '旧编辑覆盖', expectedUpdatedAt: edited.updatedAt }), /stale_snapshot/);
  const page = await graph.actionLogPage({ limit: 2 }); assert(page.nextCursor);
  const next = await graph.actionLogPage({ limit: 2, before: page.nextCursor });
  assert(!next.log.some(e => page.log.some(p => p.id === e.id)));
  checks.push('lease renewal/release, stale manual edits, cursor logs all work');
  for (const check of checks) console.log('PASS ' + check);
} finally { await graph.close(); await fs.rm(dir, { recursive: true, force: true }); }
