/** Real SQLite + central HTTP MCP; no model, private files, or production database. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {GraphMemory} from '../src/core/graph-memory.js';
import {getEmbeddingService} from '../src/core/embedding.js';
import {createNetworkMcpApp} from '../src/integrations/network-server.js';
import {issueNetworkGrant,readNetworkConfiguration} from '../src/integrations/network-config.js';
import type {ProblemReport} from '../src/core/collaboration.js';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mindpond-collaboration-'));
const configFile=path.join(dir,'accounts.json'),dbPath=path.join(dir,'central.db');
const embedding=getEmbeddingService(),original=embedding.generateEmbedding;embedding.generateEmbedding=async()=>[1,...Array(383).fill(0)];
let graph=new GraphMemory('.',{dbPath});
let network:ReturnType<typeof createNetworkMcpApp>|undefined,listener:import('node:http').Server|undefined;
const clients:Client[]=[];const tokens=new Map<string,string>();
const operator={v:1 as const,principal:'operator',operator:true,issuedAt:0,expiresAt:Number.MAX_SAFE_INTEGER};
const workspace={id:'tool-project',teamId:'developers',title:'Tool development',expectedRevision:0,members:[{principal:'suki001',roles:['reporter','reviewer'] as const},{principal:'suki',roles:['worker'] as const},{principal:'helper',roles:['worker'] as const}]};
const report:ProblemReport={summary:'Tool returns the wrong result with an empty config',project:'fixture-tool',version:'fixture-v1',environment:'Test OS; this is not a production observation',expected:'Empty config should return defaults',actual:'Throws fixture TypeError',reproduction:['Run fixture-tool with an empty JSON object'],evidence:[{label:'Observed output',content:'TypeError: missing fixture value',source:'account:suki001/private/error.log'}],attempts:['Nonempty config succeeds in this fixture'],unknowns:['Production behavior and exact cause are not verified'],acceptance:['Reporter repeats the empty-config case successfully']};
const decode=(r:any)=>JSON.parse(r.content.find((c:any)=>c.type==='text').text);
const call=async(c:Client,name:string,args:Record<string,unknown>={})=>{const r=await c.callTool({name,arguments:args});assert(!r.isError,JSON.stringify(r));return decode(r);};
const denied=async(c:Client,name:string,args:Record<string,unknown>)=>{const r=await c.callTool({name,arguments:args});assert(r.isError,`${name} unexpectedly succeeded`);return decode(r);};
const allowedHosts:string[]=['127.0.0.1:1'];
async function start(){network=createNetworkMcpApp(graph,{configuration:()=>readNetworkConfiguration(configFile),allowedHosts,maxPerAccount:5});listener=network.app.listen(0,'127.0.0.1');await new Promise<void>(r=>listener!.once('listening',r));const port=(listener.address() as import('node:net').AddressInfo).port;allowedHosts.push(`127.0.0.1:${port}`);return new URL(`http://127.0.0.1:${port}/mcp`);}
async function connect(url:URL,principal:string){const client=new Client({name:principal,version:'1'});clients.push(client);await client.connect(new StreamableHTTPClientTransport(url,{requestInit:{headers:{Authorization:`Bearer ${tokens.get(principal)}`,'X-MindPond-Session':'fixture'}}}));return client;}
try{
  for(const principal of ['suki001','suki','helper','stranger']){const tokenFile=path.join(dir,principal+'.token');await issueNetworkGrant({configFile,tokenFile,principal,personalId:principal,toolProfile:'full'});tokens.set(principal,(await fs.readFile(tokenFile,'utf8')).trim());}
  await graph.init();
  await graph.collaboration.configure({...workspace,members:workspace.members.map(m=>({...m,roles:[...m.roles]}))},operator);
  const url=await start();const [reporter,developer,helper,stranger]=await Promise.all(['suki001','suki','helper','stranger'].map(p=>connect(url,p)));
  assert.equal((await call(developer,'work_workspaces')).principal,'suki');
  assert.equal((await call(stranger,'work_workspaces')).workspaces.length,0);
  await denied(reporter,'work_workspace_configure',{...workspace,expectedRevision:1,principal:'operator',operator:true});
  await denied(developer,'work_handoff',{workspaceId:workspace.id,recipient:'suki',reviewer:'suki001',report,idempotencyKey:'role'});
  const db=(graph as any).db;
  await db.exec("CREATE TEMP TRIGGER fail_handoff_audit BEFORE INSERT ON memory_action_log WHEN NEW.action='collaboration_published' BEGIN SELECT RAISE(ABORT,'fixture rollback'); END;");
  await denied(reporter,'work_handoff',{workspaceId:workspace.id,recipient:'suki',reviewer:'suki001',report,idempotencyKey:'rollback'});
  assert.equal((await db.get('SELECT count(*) n FROM work_handoffs')).n,0);assert.equal((await db.get('SELECT count(*) n FROM work_tasks')).n,0);assert.equal((await db.get('SELECT count(*) n FROM work_collaboration_deliveries')).n,0);
  await db.exec('DROP TRIGGER fail_handoff_audit');
  const input={workspaceId:workspace.id,recipient:'suki',reviewer:'suki001',report,idempotencyKey:'problem-one',creator:'suki',principal:'suki'};
  const [published,replayed]=await Promise.all([call(reporter,'work_handoff',input),call(reporter,'work_handoff',input)]);assert.equal(published.taskId,replayed.taskId);assert.equal(published.delivery,'published');
  await denied(reporter,'work_handoff',{...input,report:{...report,actual:'Different report'},idempotencyKey:'problem-one'});
  const privateMemory=await call(reporter,'memory_save',{content:'A fixture private user note, never published.',domain:{kind:'personal',id:'suki001'},dimensions:['work'],idempotencyKey:'private'});
  await denied(developer,'memory_get',{nodeId:privateMemory.id});
  assert.equal((await call(developer,'work_inbox')).items.length,1);assert.equal((await call(stranger,'work_inbox')).items.length,0);
  await denied(stranger,'work_thread_get',{taskId:published.taskId});
  let thread=await call(developer,'work_thread_get',{taskId:published.taskId});assert.equal(thread.creator,'suki001');assert.deepEqual(thread.report,report);assert.equal(thread.receipts.length,0);
  const contextId=thread.task.context_id;
  await denied(stranger,'work_task_list',{contextId});
  await assert.rejects(graph.createWorkTask({contextId,title:'Bypass account ACL',domains:[{kind:'team',id:'developers'}]}));
  assert(!(await graph.listWorkContexts([{kind:'team',id:'developers'}])).some(v=>v.id===contextId));
  await denied(helper,'work_task_claim',{taskId:published.taskId,agentId:'suki'});
  await denied(helper,'work_ack',{taskId:published.taskId,throughSeq:published.seq,kind:'accepted',eventId:'fake'});
  const read={taskId:published.taskId,throughSeq:thread.throughSeq,kind:'read',eventId:'read-1'};await call(developer,'work_ack',read);
  assert.equal((await call(developer,'work_inbox',{unreadOnly:true})).items.length,0);
  await call(developer,'work_ack',{...read,kind:'accepted',eventId:'accept-1'});
  assert((await call(reporter,'work_inbox')).items.some((v:any)=>v.kind==='accepted'),'sender receives actual acceptance, not just publication');
  thread=await call(developer,'work_thread_get',{taskId:published.taskId});
  const question=await call(developer,'work_reply',{taskId:published.taskId,eventId:'question-1',body:'Please provide the fixture input shape; I cannot read your private path.',expectedThreadRevision:thread.threadRevision});
  assert((await call(reporter,'work_inbox')).items.some((v:any)=>v.seq===question.seq));
  thread=await call(reporter,'work_thread_get',{taskId:published.taskId});
  const revision2={...report,evidence:[...report.evidence,{label:'Actual input',content:'{}'}]};
  const replyInput={taskId:published.taskId,eventId:'evidence-2',body:'Published the actual input; other private data remains private.',expectedThreadRevision:thread.threadRevision,report:revision2};
  const updated=await call(reporter,'work_reply',replyInput);assert.equal((await call(reporter,'work_reply',replyInput)).seq,updated.seq);
  assert((await call(developer,'work_inbox',{afterSeq:published.seq,unreadOnly:true})).items.some((v:any)=>v.seq===updated.seq));
  await call(developer,'work_ack',read);assert((await call(developer,'work_inbox',{unreadOnly:true})).items.some((v:any)=>v.seq===updated.seq),'old ack cannot consume new evidence');
  assert.deepEqual((await call(developer,'work_thread_get',{taskId:published.taskId,reportVersion:1})).report,report);
  assert.equal((await call(developer,'work_thread_get',{taskId:published.taskId,reportVersion:1})).throughSeq,0,'historical reports cannot acknowledge newer evidence');
  const originalAll=db.all.bind(db);
  db.all=async(sql:string,...args:any[])=>{const rows=await originalAll(sql,...args);if(sql.startsWith('SELECT * FROM work_collaboration_events WHERE task_id=?'))await db.run('UPDATE work_handoffs SET thread_revision=thread_revision+1 WHERE task_id=?',[published.taskId]);return rows;};
  try{await assert.rejects(graph.collaboration.get({taskId:published.taskId},operator),/changed while reading/);}finally{db.all=originalAll;}
  thread=await call(developer,'work_thread_get',{taskId:published.taskId});
  const parallel=await Promise.all([developer,await connect(url,'suki')].map((c,index)=>c.callTool({name:'work_task_claim',arguments:{taskId:published.taskId,eventId:'claim-'+index,agentId:'spoofed-agent',expectedRevision:thread.task.revision}})));
  assert.equal(parallel.filter(r=>!r.isError).length,1);const winner=parallel.findIndex(r=>!r.isError);const claim=decode(parallel[winner]);assert.equal(claim.task.assignee,'suki');assert.equal((await call(developer,'work_task_claim',{taskId:published.taskId,eventId:'claim-'+winner,agentId:'spoofed-agent',expectedRevision:thread.task.revision})).leaseToken,claim.leaseToken,'lost claim response recovers the same private lease receipt');
  await call(developer,'work_task_renew',{taskId:published.taskId,agentId:'suki001',leaseToken:claim.leaseToken});
  assert(!(JSON.stringify(await call(helper,'work_thread_get',{taskId:published.taskId}))).includes(claim.leaseToken));
  const submit={taskId:published.taskId,agentId:'whatever',eventId:'submit-1',expectedRevision:claim.task.revision,leaseToken:claim.leaseToken,status:'submitted',reason:'Fixture correction is ready for reporter reproduction.',resultRefs:['fixture:repair-version-2']};
  const submitted=await call(developer,'work_task_transition',submit);
  await denied(developer,'work_task_transition',{...submit,eventId:'unauthorized-accept',status:'completed',expectedRevision:submitted.revision});
  assert.equal((await call(developer,'work_task_transition',submit)).revision,submitted.revision,'submission replay does not append events');
  thread=await call(reporter,'work_thread_get',{taskId:published.taskId});
  await call(reporter,'work_reply',{...replyInput,eventId:'new-report-after-submit',expectedThreadRevision:thread.threadRevision,report:{...revision2,unknowns:['A newly observed fixture condition still needs worker verification.']}});
  await denied(reporter,'work_task_transition',{taskId:published.taskId,agentId:'suki001',eventId:'stale-accept',expectedRevision:submitted.revision,status:'completed',reason:'Should not accept outdated report'});
  thread=await call(developer,'work_thread_get',{taskId:published.taskId});assert.equal(thread.task.status,'blocked');
  const reclaimed=await call(developer,'work_task_claim',{taskId:published.taskId,eventId:'reclaim-2',agentId:'suki',expectedRevision:thread.task.revision});
  const resubmitted=await call(developer,'work_task_transition',{...submit,eventId:'submit-2',expectedRevision:reclaimed.task.revision,leaseToken:reclaimed.leaseToken});
  const completed=await call(reporter,'work_task_transition',{taskId:published.taskId,agentId:'pretend-suki',eventId:'verified',expectedRevision:resubmitted.revision,status:'completed',reason:'Reporter actually repeated the fixture acceptance case.'});assert.equal(completed.status,'completed');
  await denied(reporter,'work_reply',{...replyInput,eventId:'late',expectedThreadRevision:(await call(reporter,'work_thread_get',{taskId:published.taskId})).threadRevision});
  assert.equal((await db.get('SELECT count(*) n FROM nodes')).n,1,'collaboration does not vectorize or become memory');
  await graph.collaboration.configure({...workspace,expectedRevision:1,members:workspace.members.filter(m=>m.principal!=='helper').map(m=>({...m,roles:[...m.roles]}))},operator);
  await denied(helper,'work_thread_get',{taskId:published.taskId});assert.equal((await call(helper,'work_inbox')).items.length,0);
  await Promise.all(clients.splice(0).map(c=>c.close()));await network!.close(listener);listener=undefined;await graph.close();
  graph=new GraphMemory('.',{dbPath});await graph.init();const restartUrl=await start();const resumed=await connect(restartUrl,'suki');
  assert.equal((await call(resumed,'work_thread_get',{taskId:published.taskId})).task.status,'completed');assert((await call(resumed,'work_inbox')).items.some((v:any)=>v.kind==='completed'));
  assert.equal((await call(await connect(restartUrl,'suki001'),'work_handoff',input)).taskId,published.taskId,'response loss/restart keeps original receipt');
  console.log('PASS collaboration: authenticated identities/roles; atomic rollback/idempotency; complete versioned evidence; inbox cursors and old ack; account isolation; exclusive leases and reviewer acceptance; revocation/restart; no graph-memory pollution');
}finally{await Promise.allSettled(clients.map(c=>c.close()));if(network)await network.close(listener);await graph.close();embedding.generateEmbedding=original;await fs.rm(dir,{recursive:true,force:true});}
