/** Real DB integration: user taxonomy, dynamic prompts, scope and legacy storage. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {GraphMemory} from '../src/core/graph-memory.js';
import {getEmbeddingService} from '../src/core/embedding.js';
import {MemoryRevisions} from '../src/core/memory-revisions.js';
import {hostOperations,dimensionsSchema} from '../src/core/host-contract.js';
import {organizationTask} from '../src/core/organization-policy.js';
import {MemoryPipelineManager} from '../src/core/memory-pipeline.js';
import {memorySavePolicyPayload} from '../src/core/save-policy.js';
import {LEGACY_DIMENSION_CONFIGURATION} from '../src/core/dimension-config.js';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mindpond-custom-dim-'));
const old=process.env.MEMORY_DB_PATH;process.env.MEMORY_DB_PATH=path.join(dir,'pond.db');
const embed=getEmbeddingService();const generate=embed.generateEmbedding;embed.generateEmbedding=async()=>[1,...Array(383).fill(0)];
let graph=new GraphMemory();
try{
  await graph.init();
  const initial=await graph.getDimensionConfiguration();
  assert.equal(initial.defaultDimension,'work');
  assert.deepEqual(initial.definitions.slice(0,5).map(d=>d.id),['profile','commitment','environment','work','practice']);
  assert.equal(initial.definitions.length,9,'five preferred identities plus explicit legacy compatibility');
  assert(initial.definitions.slice(5).every(d=>d.label.includes('历史兼容')));
  const initialPolicy=await graph.getDimensionPolicy();
  assert.equal(memorySavePolicyPayload(initialPolicy).example.memberships[0].memoryType,'work');
  assert.deepEqual(memorySavePolicyPayload(initialPolicy).example.dimensions,['work']);
  const fresh=await graph.saveMemory('A new installation uses its configured work default.');
  assert.equal((await graph.getNodeById(fresh.id))?.dimension,'work');
  await graph.deleteNode(fresh.id,'Remove default-preset fixture before replacing the taxonomy.');
  const oldPath=path.join(dir,'old-template.db');
  let oldGraph=new GraphMemory('.', {dbPath:oldPath});
  try {
    await oldGraph.init();
    await (oldGraph as any).db.run('UPDATE memory_dimension_config SET revision=1,payload=? WHERE id=1',[JSON.stringify(LEGACY_DIMENSION_CONFIGURATION)]);
    await oldGraph.close();oldGraph=new GraphMemory('.', {dbPath:oldPath});await oldGraph.init();
    assert.deepEqual(await oldGraph.getDimensionConfiguration(),LEGACY_DIMENSION_CONFIGURATION,'even untouched revision=1 existing configurations must survive an upgrade');
    const legacyPolicy=await oldGraph.getDimensionPolicy();
    assert.equal(memorySavePolicyPayload(legacyPolicy).example.memberships[0].memoryType,'fact','live policy overrides the published default');
  } finally {await oldGraph.close();}
  const ids=['人物画像','procedure','constructor',...Array.from({length:17},(_,i)=>'custom-'+i)];
  const input={expectedRevision:initial.revision,defaultDimension:ids[0],prompt:'CLASSIFICATION-CUSTOM-PROMPT: use only evidenced identities.',definitions:ids.map(id=>({id,label:'用户 '+id,description:'Meaning of '+id,instructions:'RULE-'+id+': preserve conditions.',color:'#aabbcc',enabled:true}))};
  const config=await graph.configureDimensions(input);assert.equal(config.definitions.length,20);
  await assert.rejects(graph.configureDimensions(input),/revision conflict/);
  assert.equal(dimensionsSchema.parse(ids).length,20,'schema must not retain a four-dimension cap');
  const saved=await graph.saveMemory('A complete reusable profile and procedure under twenty user identities.',{dimensions:ids});
  assert.equal(saved.memberships.length,20,'derived dimension placements must not inherit the old 16-dimension limit');
  const node=await graph.getNodeById(saved.id);assert.deepEqual(new Set(node?.dimensions),new Set(ids));
  assert.equal(node?.dimension,'人物画像','SQLite compatibility scalar must not become the public identity');
  assert.equal((await graph.listNodes({dimension:'procedure'})).nodes.length,1);
  assert.equal((await graph.getStats()).byDimension.procedure,1);
  const view=await graph.getFullGraph(20);assert.ok(view.nodes.some(n=>n.dimensions?.includes('procedure')));
  assert.equal((await graph.taskBrief('Reusable procedure')).dimensionPolicy.revision,config.revision);
  await assert.rejects(graph.saveMemory('unknown',{dimensions:['never-configured']}),/Unknown or archived/);
  await assert.rejects(graph.saveMemory('event identity',{dimensions:['event']}),/reserved evidence/);
  await assert.rejects(graph.configureDimensions({...input,expectedRevision:config.revision,definitions:input.definitions.slice(1),defaultDimension:'procedure'}),/Referenced dimension/);
  const defaultSave=await graph.saveMemory('Default classification uses the user choice.');assert.equal((await graph.getNodeById(defaultSave.id))?.dimension,'人物画像');
  const prior=await graph.getNodeById(defaultSave.id,{trackAccess:false});
  const edited=await graph.editMemory(defaultSave.id,{dimensions:['constructor'],expectedUpdatedAt:prior!.updatedAt,reason:'classification test'});
  await graph.restoreMemoryEdit(defaultSave.id,{revisionId:edited.revisionId,expectedUpdatedAt:(await graph.getNodeById(defaultSave.id,{trackAccess:false}))!.updatedAt,reason:'undo classification test'});
  assert.equal((await graph.getNodeById(defaultSave.id))?.dimension,'人物画像','restore must restore custom primary dimension');
  const unusual=await graph.addMembership(defaultSave.id,'project:original','old-topic');
  const anchorBefore=await graph.getNodeById(defaultSave.id,{trackAccess:false});
  await graph.editMemory(defaultSave.id,{anchors:[{text:'User taxonomy',basis:'user choice',spaceId:unusual.spaceId,memoryType:unusual.memoryType}],expectedUpdatedAt:anchorBefore!.updatedAt});
  const originalNode=await graph.getNodeById(defaultSave.id,{trackAccess:false});
  await assert.rejects(graph.editMemory(defaultSave.id,{dimensions:['constructor'],replaceMembershipIds:['foreign-id'],expectedUpdatedAt:originalNode!.updatedAt,reason:'bad scope'}),/foreign/);
  const moved=await graph.editMemory(defaultSave.id,{dimensions:['constructor'],replaceMembershipIds:[unusual.id],anchors:[{text:'User taxonomy',basis:'user choice',spaceId:unusual.spaceId,memoryType:'constructor'}],expectedUpdatedAt:originalNode!.updatedAt,reason:'explicit scoped migration'});
  const placements=await graph.getMemberships(defaultSave.id,{activeOnly:true});
  assert.ok(!placements.some(m=>m.id===unusual.id));assert.ok(placements.some(m=>m.spaceId==='project:original'&&m.memoryType==='constructor'));
  await graph.restoreMemoryEdit(defaultSave.id,{revisionId:moved.revisionId,expectedUpdatedAt:(await graph.getNodeById(defaultSave.id,{trackAccess:false}))!.updatedAt,reason:'undo scoped migration'});
  assert.ok((await graph.getMemberships(defaultSave.id,{activeOnly:true})).some(m=>m.id===unusual.id));
  assert.equal((await graph.getNodeById(defaultSave.id))?.anchors?.[0].memoryType,'old-topic','undo restores the original scoped anchor');
  const legacyBefore=await graph.getNodeById(defaultSave.id,{trackAccess:false});
  const legacyEdit=await graph.editMemory(defaultSave.id,{dimensions:['constructor'],expectedUpdatedAt:legacyBefore!.updatedAt,reason:'legacy-format revision fixture'});
  const db=(graph as any).db;const oldRow=await db.get('SELECT before_snapshot,after_snapshot FROM memory_edit_revisions WHERE id=?',[legacyEdit.revisionId]);
  const oldBefore=JSON.parse(oldRow.before_snapshot),oldAfter=JSON.parse(oldRow.after_snapshot);delete oldBefore.node.primary_dimension;delete oldAfter.node.primary_dimension;
  await db.run('UPDATE memory_edit_revisions SET before_snapshot=?,after_snapshot=?,after_fingerprint=? WHERE id=?',[JSON.stringify(oldBefore),JSON.stringify(oldAfter),await new MemoryRevisions(db).fingerprint(defaultSave.id,true),legacyEdit.revisionId]);
  await graph.restoreMemoryEdit(defaultSave.id,{revisionId:legacyEdit.revisionId,expectedUpdatedAt:(await graph.getNodeById(defaultSave.id,{trackAccess:false}))!.updatedAt,reason:'legacy undo remains compatible'});
  assert.equal((await graph.getNodeById(defaultSave.id))?.dimension,'人物画像');
  const legacyNull=await graph.saveMemory('An imported legacy memory with no stored primary identity.',{dimensions:['constructor']});
  await db.run("UPDATE nodes SET dimension='fact',dimensions=NULL,primary_dimension=NULL WHERE id=?",[legacyNull.id]);
  await db.run("UPDATE memory_memberships SET memory_type='fact' WHERE memory_id=?",[legacyNull.id]);
  const nullBefore=await graph.getNodeById(legacyNull.id,{trackAccess:false});
  const nullEdit=await graph.editMemory(legacyNull.id,{dimensions:['constructor'],expectedUpdatedAt:nullBefore!.updatedAt,reason:'classify legacy null primary'});
  await graph.restoreMemoryEdit(legacyNull.id,{revisionId:nullEdit.revisionId,expectedUpdatedAt:(await graph.getNodeById(legacyNull.id,{trackAccess:false}))!.updatedAt,reason:'restore legacy null primary exactly'});
  assert.equal((await db.get('SELECT primary_dimension FROM nodes WHERE id=?',[legacyNull.id])).primary_dimension,null,'a recorded null is restored exactly, rather than inferred');
  await graph.deleteNode(legacyNull.id,'Remove the isolated legacy-null fixture before testing the unrelated custom configuration archive.');
  const policy=await graph.getDimensionPolicy();assert.ok(memorySavePolicyPayload(policy).text.includes('CLASSIFICATION-CUSTOM-PROMPT'));
  const op=hostOperations(graph).find(o=>o.name==='memory_dimension_policy')!;assert.ok((await op.run({})).instructions.includes('RULE-procedure'));
  await graph.saveMemory('Another complete unit for custom procedure review.',{dimensions:['procedure'],idempotencyKey:'archive-retry'});
  const request=await graph.claimOrganizationJob({spaceId:'personal:default',memoryType:'procedure',limit:8});assert.ok(request);
  assert.ok(organizationTask(request).prompt?.includes('RULE-procedure'));
  const raw=await graph.ingestTranscript('The user provided durable profile evidence.','extract-session','raw-1');
  const pipeline=new MemoryPipelineManager(graph,undefined);const job=await pipeline.getExtractionJob({sessionId:'extract-session'});assert.equal(job?.id,raw.extractionJobId);
  assert.ok(job?.prompt.includes('CLASSIFICATION-CUSTOM-PROMPT'));
  const result=await pipeline.commitExtraction(job!.id,JSON.stringify({memories:[{content:'Verified custom procedure evidence.',type:'procedure',dimensions:['procedure'],priority:6,source_message_ids:['msg-0']}]}),job!.attempts);
  assert.equal(result.atomsCreated,1);
  const staleRaw=await graph.ingestTranscript('Another profile observation.','stale-session','stale-raw');
  const staleJob=await pipeline.getExtractionJob({sessionId:'stale-session'});assert.equal(staleJob?.id,staleRaw.extractionJobId);
  const archived=await graph.configureDimensions({...input,expectedRevision:config.revision,definitions:input.definitions.map(d=>({...d,enabled:d.id!=='procedure'}))});
  await assert.rejects(pipeline.commitExtraction(staleJob!.id,JSON.stringify({memories:[]}),staleJob!.attempts),/stale_extraction_lease/);
  const renewed=await pipeline.getExtractionJob({sessionId:'stale-session'});assert.equal(renewed?.id,staleJob!.id);assert.ok(renewed!.attempts>staleJob!.attempts);
  await assert.rejects(graph.saveMemory('new archived memory',{dimensions:['procedure']}),/archived/);
  const replay=await graph.saveMemory('Another complete unit for custom procedure review.',{dimensions:['procedure'],idempotencyKey:'archive-retry'});assert.ok(replay.id,'exact committed retries remain valid after archiving');
  await assert.rejects(graph.validateOrganizationPlan(request!.id,{operations:[]}),/dimension policy changed/);
  assert.ok((await graph.search({nodeId:saved.id,maxDepth:0}))[0].node.dimensions?.includes('procedure'),'archiving must not hide old knowledge');
  await graph.close();graph=new GraphMemory();await graph.init();assert.equal((await graph.getDimensionConfiguration()).revision,archived.revision);assert.ok((await graph.getNodeById(saved.id))?.dimensions?.includes('procedure'));
  console.log('PASS custom dimensions: 20 identities, user default, legacy SQLite compatibility, dynamic save/organize/extract prompts, archive, revision fencing and restart');
}finally{await graph.close();embed.generateEmbedding=generate;if(old===undefined)delete process.env.MEMORY_DB_PATH;else process.env.MEMORY_DB_PATH=old;await fs.rm(dir,{recursive:true,force:true});}
