/** Deterministic real MCP/SQLite loop, including independent DB connections. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import readline from 'node:readline';
import {fileURLToPath} from 'node:url';
import {Client} from '@modelcontextprotocol/sdk/client/index.js';
import {StreamableHTTPClientTransport} from '@modelcontextprotocol/sdk/client/streamableHttp.js';
import {LATEST_PROTOCOL_VERSION} from '@modelcontextprotocol/sdk/types.js';
import {GraphMemory} from '../src/core/graph-memory.js';
import {HostSessionService} from '../src/integrations/host-session.js';
import {createNetworkMcpApp} from '../src/integrations/network-server.js';
import {issueNetworkGrant,readNetworkConfiguration} from '../src/integrations/network-config.js';
import type {ProblemReport} from '../src/core/collaboration.js';
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'mindpond-loop-'));
const dbPath=path.join(temp,'memory.db'),configFile=path.join(temp,'accounts.json');
const operator={v:1 as const,principal:'operator',operator:true,issuedAt:0,expiresAt:Number.MAX_SAFE_INTEGER};
const actor=(principal:string)=>({...operator,principal,operator:false});
const report:ProblemReport={summary:'Fixture code/verification loop',project:'fixture',version:'baseline',environment:'Synthetic test only',expected:'Fixture tests pass',actual:'One failing assertion',reproduction:['Run fixture test'],evidence:[{label:'Baseline',content:'Fixture assertion fails'}],attempts:[],unknowns:[],acceptance:['Fixture test passes']};
let graph=new GraphMemory('.',{dbPath}),peer:GraphMemory|undefined;
let network:ReturnType<typeof createNetworkMcpApp>|undefined,listener:import('node:http').Server|undefined;
let worker:ReturnType<typeof spawn>|undefined;
const clients:Client[]=[],tokens=new Map<string,string>();
const transports=new Map<string,StreamableHTTPClientTransport>();
const decode=(r:any)=>JSON.parse(r.content.find((c:any)=>c.type==='text').text);
const call=async(c:Client,name:string,args:Record<string,unknown>={})=>{const r=await c.callTool({name,arguments:args});assert(!r.isError,JSON.stringify(r));return decode(r);};
const deny=async(c:Client,name:string,args:Record<string,unknown>)=>{const r=await c.callTool({name,arguments:args});assert(r.isError,`${name} unexpectedly succeeded`);return decode(r);};
async function ready(predicate:()=>Promise<boolean>){const deadline=Date.now()+5000;while(!await predicate()){assert(Date.now()<deadline,'wait did not become active');await new Promise(r=>setTimeout(r,15));}}
async function start(){
  const hosts:string[]=['127.0.0.1:1'];
  network=createNetworkMcpApp(graph,{configuration:()=>readNetworkConfiguration(configFile),allowedHosts:hosts});
  listener=network.app.listen(0,'127.0.0.1');await new Promise<void>(r=>listener!.once('listening',r));
  const port=(listener.address() as import('node:net').AddressInfo).port;hosts.push(`127.0.0.1:${port}`);
  return new URL(`http://127.0.0.1:${port}/mcp`);
}
async function connect(url:URL,principal:string){const c=new Client({name:principal,version:'fixture'});clients.push(c);const transport=new StreamableHTTPClientTransport(url,{requestInit:{headers:{Authorization:`Bearer ${tokens.get(principal)}`,'X-MindPond-Session':'loop'}}});transports.set(principal,transport);await c.connect(transport);return c;}
try{
  for(const principal of ['writer','verifier','outsider']){
    const tokenFile=path.join(temp,principal+'.token');await issueNetworkGrant({configFile,tokenFile,principal,personalId:'shared-personal',toolProfile:'work'});tokens.set(principal,(await fs.readFile(tokenFile,'utf8')).trim());
  }
  await graph.init();
  const workspace={id:'loop-project',teamId:'fixture-team',title:'Fixture loop',expectedRevision:0,members:[{principal:'writer',roles:['reporter','worker'] as Array<'reporter'|'worker'>},{principal:'verifier',roles:['reviewer'] as Array<'reviewer'>}]};
  await graph.collaboration.configure(workspace,operator);
  const url=await start(),writer=await connect(url,'writer'),verifier=await connect(url,'verifier'),outsider=await connect(url,'outsider');
  assert((await writer.listTools()).tools.some(t=>t.name==='work_wait'));
  const idle=call(verifier,'work_wait',{until:'inbox_update',waitMs:3000});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.length);
  const published=await call(writer,'work_handoff',{workspaceId:workspace.id,recipient:'writer',reviewer:'verifier',report,maxIterations:2,idempotencyKey:'loop'});
  assert.equal((await idle).items[0].taskId,published.taskId);
  const taskId=published.taskId;
  const thread=await call(writer,'work_thread_get',{taskId});
  await deny(outsider,'work_wait',{taskId,until:'iteration_submitted',waitMs:100});
  assert.equal((await call(outsider,'work_activity')).tasks.length,0);
  await deny(verifier,'work_wait',{taskId,until:'verification_result',waitMs:100});
  const reviewerWait=call(verifier,'work_wait',{taskId,until:'iteration_submitted',afterSeq:published.seq,waitMs:3000});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).tasks[0].waits.length);
  const claimed=await call(writer,'work_task_claim',{taskId,eventId:'claim-one',agentId:'spoof',expectedRevision:thread.task.revision});
  const submission={taskId,eventId:'iteration-one',expectedRevision:claimed.task.revision,leaseToken:claimed.leaseToken,codeVersion:'fixture-sha-one',artifactRef:'fixture://repository/commit/one',summary:'First correction',resultRefs:['fixture://diff/one']};
  const round=await call(writer,'work_iteration_submit',submission);
  assert.equal((await call(writer,'work_iteration_submit',submission)).roundId,round.roundId);
  assert.equal((await reviewerWait).iteration.codeVersion,submission.codeVersion);
  await deny(verifier,'work_task_transition',{taskId,eventId:'bypass',agentId:'verifier',expectedRevision:round.taskRevision,status:'completed',reason:'Must not bypass version-bound verification'});
  await deny(writer,'work_task_transition',{taskId,eventId:'premature-edit',agentId:'writer',expectedRevision:round.taskRevision,status:'open',reason:'Must not edit before verification'});
  const waitInput={taskId,until:'verification_result',roundId:round.roundId,codeVersion:round.codeVersion,afterSeq:round.seq,waitMs:3000};
  const writerWait=call(writer,'work_wait',waitInput);
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).tasks[0].waits.some(w=>w.principal==='writer'));
  const reviewed=await call(verifier,'work_thread_get',{taskId});
  await call(verifier,'work_ack',{taskId,throughSeq:round.seq,kind:'read',eventId:'read-code'});
  const timeout=await call(writer,'work_wait',{...waitInput,waitMs:100});
  assert.equal(timeout.status,'timeout','read receipts do not resolve a verification wait');assert.equal(timeout.resume.roundId,round.roundId);
  await deny(writer,'work_verification_report',{taskId,roundId:round.roundId,codeVersion:round.codeVersion,eventId:'wrong-role',expectedRevision:reviewed.task.revision,verdict:'passed',summary:'Not a reviewer',evidence:[{label:'Fixture',content:'Unverified'}]});
  await deny(verifier,'work_verification_report',{taskId,roundId:round.roundId,codeVersion:'wrong-version',eventId:'wrong-code',expectedRevision:reviewed.task.revision,verdict:'passed',summary:'Wrong code',evidence:[{label:'Fixture',content:'Different artifact'}]});
  const failure={taskId,roundId:round.roundId,codeVersion:round.codeVersion,eventId:'verification-one',expectedRevision:reviewed.task.revision,verdict:'changes_requested',summary:'Fixture still fails on empty input',evidence:[{label:'Test output',content:'fixture empty input: expected 0, received undefined'}]};
  const feedback=await call(verifier,'work_verification_report',failure);
  const received=await writerWait;assert.equal(received.status,'matched');assert.equal(received.iteration.result.verdict,'changes_requested');
  assert.equal((await call(verifier,'work_verification_report',failure)).seq,feedback.seq);
  assert.equal((await call(writer,'work_wait',waitInput)).iteration.result.evidence[0].content,failure.evidence[0].content,'result already present is returned immediately');
  const next=await call(writer,'work_task_claim',{taskId,eventId:'claim-two',agentId:'writer',expectedRevision:feedback.taskRevision});
  const second=await call(writer,'work_iteration_submit',{...submission,eventId:'iteration-two',expectedRevision:next.task.revision,leaseToken:next.leaseToken,codeVersion:'fixture-sha-two',artifactRef:'fixture://repository/commit/two'});
  await deny(verifier,'work_verification_report',{...failure,eventId:'late-first',expectedRevision:second.taskRevision});
  const independentWait=call(writer,'work_wait',{...waitInput,roundId:second.roundId,codeVersion:second.codeVersion,afterSeq:second.seq});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).tasks[0].waits.length);
  peer=new GraphMemory('.',{dbPath});await peer.init();
  const passed=await peer.collaboration.verifyIteration({taskId,roundId:second.roundId,codeVersion:second.codeVersion,eventId:'verification-two',expectedRevision:second.taskRevision,verdict:'passed',summary:'Fixture cases pass',evidence:[{label:'Actual output',content:'2 fixture tests passed'}]},actor('verifier'));
  assert.equal((await independentWait).iteration.state,'passed','independent connection wakes via durable DB fallback');
  assert.equal(passed.status,'completed');
  const completed=await call(writer,'work_thread_get',{taskId});assert.equal(completed.iterations.length,2);assert.equal(completed.task.status,'completed');assert(!JSON.stringify(completed).includes(next.leaseToken));
  // A second task exercises changed requirements, cancellation and limits.
  const another=await call(writer,'work_handoff',{workspaceId:workspace.id,recipient:'writer',reviewer:'verifier',report,maxIterations:1,idempotencyKey:'another'});
  const claimedAgain=await call(writer,'work_task_claim',{taskId:another.taskId,eventId:'claim-three',agentId:'writer',expectedRevision:1});
  const pending=await call(writer,'work_iteration_submit',{...submission,taskId:another.taskId,eventId:'iteration-three',expectedRevision:claimedAgain.task.revision,leaseToken:claimedAgain.leaseToken});
  const invalidated=call(writer,'work_wait',{...waitInput,taskId:another.taskId,roundId:pending.roundId,codeVersion:pending.codeVersion,afterSeq:pending.seq});
  const beforeReply=await call(writer,'work_thread_get',{taskId:another.taskId});
  await call(writer,'work_reply',{taskId:another.taskId,eventId:'new-requirements',expectedThreadRevision:beforeReply.threadRevision,body:'A new fixture requirement',report:{...report,expected:'Changed requirement'}});
  assert.equal((await invalidated).status,'superseded');
  await deny(writer,'work_task_claim',{taskId:another.taskId,eventId:'over-budget',agentId:'writer',expectedRevision:pending.taskRevision+1});
  assert.equal((await call(verifier,'work_wait',{taskId:another.taskId,until:'iteration_submitted',afterSeq:pending.seq,waitMs:100})).reason,'iteration_budget_exhausted');
  console.log('PASS loop rounds, delayed replies, invalidation and budget');
  const cancel=new AbortController();
  const cancelled=graph.collaboration.wait({until:'inbox_update',afterSeq:1e9,waitMs:5000},actor('writer'),{signal:cancel.signal});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.length);cancel.abort();assert.equal((await cancelled).status,'cancelled');
  const cap=new AbortController();const waits=Array.from({length:8},()=>graph.collaboration.wait({until:'inbox_update',afterSeq:1e9,waitMs:5000},actor('writer'),{signal:cap.signal}));
  await ready(async()=>(await graph.collaboration.activity({},operator)).incomingWaits.filter(w=>w.principal==='writer').length===8);
  await assert.rejects(graph.collaboration.wait({until:'inbox_update',afterSeq:1e9,waitMs:5000},actor('writer')),/Too many/);cap.abort();await Promise.all(waits);
  console.log('PASS waiter cancellation and per-account cap');
  // RPC cancellation is propagated by the real MCP transport.
  const clientAbort=new AbortController();
  const rpc=writer.callTool({name:'work_wait',arguments:{until:'inbox_update',afterSeq:1e9,waitMs:5000}},undefined,{signal:clientAbort.signal});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='writer'));clientAbort.abort();await assert.rejects(rpc);
  await ready(async()=>!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='writer'));
  const disconnected=new AbortController();
  const raw=fetch(url,{method:'POST',signal:disconnected.signal,headers:{Authorization:`Bearer ${tokens.get('writer')}`,'X-MindPond-Session':'loop','mcp-session-id':transports.get('writer')!.sessionId!,'mcp-protocol-version':LATEST_PROTOCOL_VERSION,Accept:'application/json, text/event-stream','Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:'raw-disconnect',method:'tools/call',params:{name:'work_wait',arguments:{until:'inbox_update',afterSeq:1e9,waitMs:5000}}})});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='writer'));disconnected.abort();await assert.rejects(raw);
  await ready(async()=>!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='writer'));
  console.log('PASS real MCP request cancellation');
  // Revoking a bearer while its long poll is outstanding denies its result.
  const revoked=verifier.callTool({name:'work_wait',arguments:{until:'inbox_update',afterSeq:1e9,waitMs:5000}});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='verifier'));
  const config=await readNetworkConfiguration(configFile);await fs.writeFile(configFile,JSON.stringify({...config,grants:config.grants.filter(g=>g.principal!=='verifier')}));
  assert((await revoked).isError,'revocation is checked during outstanding wait');
  await fs.writeFile(configFile,JSON.stringify(config));
  console.log('PASS outstanding bearer revocation');
  const native=new HostSessionService(graph,[{kind:'personal',id:'shared-personal'}],'writer');
  assert.equal((await native.call('fixture-native','work_wait',{until:'inbox_update',afterSeq:1e9,waitMs:100}) as any).status,'timeout');
  console.log('PASS native service wait');
  worker=spawn(process.execPath,[fileURLToPath(new URL('../dist/integrations/host-worker.js',import.meta.url))],{env:{...process.env,MEMORY_DB_PATH:dbPath,MEMORY_TRUST_PRINCIPAL:'writer',MEMORY_TRUST_DOMAINS:JSON.stringify([{kind:'personal',id:'shared-personal'}]),EMBEDDING_ZH_ENABLED:'false'},stdio:['pipe','pipe','pipe']});
  let workerLogs='';worker.stderr!.on('data',data=>workerLogs+=data);
  const pendingRpc=new Map<string,{resolve:(response:any)=>void;reject:(error:Error)=>void;timer:ReturnType<typeof setTimeout>}>();
  worker.once('exit',()=>{for(const rpc of pendingRpc.values()){clearTimeout(rpc.timer);rpc.reject(Error('Fixture worker exited: '+workerLogs));}pendingRpc.clear();});
  const lines=readline.createInterface({input:worker.stdout!});lines.on('line',line=>{const response=JSON.parse(line),rpc=pendingRpc.get(response.id);if(rpc){clearTimeout(rpc.timer);rpc.resolve(response);pendingRpc.delete(response.id);}});
  const nativeRpc=(id:string,tool:string,args:unknown={})=>new Promise<any>((resolve,reject)=>{const timer=setTimeout(()=>{pendingRpc.delete(id);reject(Error('Fixture native RPC timed out: '+workerLogs));},5000);pendingRpc.set(id,{resolve,reject,timer});worker!.stdin!.write(JSON.stringify({id,sessionId:'native-loop',tool,args})+'\n');});
  await nativeRpc('identity','__mindpond_host_identity');
  const nativeWait=nativeRpc('native-wait','work_wait',{until:'inbox_update',afterSeq:1e9,waitMs:3000});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='writer'));
  const concurrent=await Promise.race([nativeRpc('native-read','memory_capabilities'),new Promise<never>((_,reject)=>{const timer=setTimeout(()=>reject(Error('Native wait blocked another request')),1000);timer.unref();})]);
  assert(concurrent.result.features.includes('collaboration-wait'));
  worker.stdin!.write(JSON.stringify({cancel:'native-wait'})+'\n');assert.equal((await nativeWait).result.status,'cancelled');
  const exit=new Promise<void>(resolve=>worker!.once('exit',()=>resolve()));worker.kill('SIGTERM');await exit;worker=undefined;lines.close();
  console.log('PASS concurrent native RPC and cancellation');
  const duringShutdown=call(writer,'work_wait',{until:'inbox_update',afterSeq:1e9,waitMs:5000});
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.some(w=>w.principal==='writer'));
  await network.close(listener);listener=undefined;assert.equal((await duringShutdown).status,'cancelled');
  await Promise.all(clients.splice(0).map(c=>c.close()));await peer.close();peer=undefined;await graph.close();
  graph=new GraphMemory('.',{dbPath});await graph.init();
  assert.equal((await graph.collaboration.wait({...waitInput,roundId:second.roundId,codeVersion:second.codeVersion,afterSeq:second.seq},actor('writer')) as any).iteration.state,'passed','restart preserves exact current-round result');
  assert.equal((await graph.collaboration.wait(waitInput,actor('writer')) as any).status,'superseded','old-round replies cannot drive a newer iteration after restart');
  await graph.collaboration.configure({id:'self-review-fixture',teamId:'fixture-team',title:'Same account guard',expectedRevision:0,members:[{principal:'writer',roles:['reporter','worker','reviewer']}]},operator);
  const self=await graph.collaboration.handoff({workspaceId:'self-review-fixture',recipient:'writer',reviewer:'writer',report,idempotencyKey:'self-review'},actor('writer'));
  const selfThread=await graph.collaboration.get({taskId:self.taskId},actor('writer'));
  const selfClaim=await graph.collaboration.taskMutation('claim',{taskId:self.taskId,eventId:'self-claim',expectedRevision:selfThread.task.revision,agentId:'writer'},actor('writer'));
  await assert.rejects(()=>graph.collaboration.submitIteration({...submission,taskId:self.taskId,eventId:'self-iteration',expectedRevision:selfClaim.task.revision,leaseToken:selfClaim.leaseToken},actor('writer')),/distinct authenticated/);
  const stopping=graph.collaboration.wait({until:'inbox_update',afterSeq:1e9,waitMs:5000},actor('writer'));
  await ready(async()=>!!(await graph.collaboration.activity({},operator)).incomingWaits.length);await graph.close();assert.equal((await stopping).status,'cancelled');
  console.log('PASS collaboration wait: real MCP two-round loop; exact version/role/receipt guards; no DB lock while waiting; timeout/read separation; independent-connection fallback; evidence/history/restart; invalidation/budget; caps/cancellation/revocation/native/shutdown');
}finally{
  worker?.kill('SIGTERM');await Promise.allSettled(clients.map(c=>c.close()));if(network)await network.close(listener);await peer?.close();await graph.close();await fs.rm(temp,{recursive:true,force:true});
}
