import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {open} from 'sqlite';
import sqlite3 from 'sqlite3';
import {GraphMemory} from '../src/core/graph-memory.js';
import type {SourceReference,SynthesizeOperation} from '../src/core/growth.js';
import {capabilities,hostOperations} from '../src/core/host-contract.js';

const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mindpond-growth-'));
process.env.MEMORY_DB_PATH=path.join(dir,'pond.db');
process.env.EMBEDDING_ZH_ENABLED='false';
let g=new GraphMemory();let other:GraphMemory|undefined;
const scope={spaceId:'sample-project/runtime',memoryType:'knowledge'};
const ref=(name:string,revision='r1',context='main'):SourceReference=>({uri:`repo:sample-project/${name}.ts`,context,revision,fingerprint:`${name}-${revision}`});
const create=async(name:string)=>g.saveMemory(`${name}: explicit code behavior, its constraints and observed evidence.`,{memberships:[scope],sourceRefs:[ref(name)],idempotencyKey:`test-save-${name}`});
const member=(saved:any)=>saved.memberships[0].id as string;
async function synthesis(ids:string[],target?:string) {
  const job=await g.claimOrganizationJob({...scope,membershipIds:[...ids,...target?[target]:[]]});assert(job);
  const op:SynthesizeOperation={kind:'synthesize',membershipIds:ids,targetMembershipId:target,content:'The combined workflow preserves explicit responsibilities and conditions; reviewed subset only.',reason:'These sources establish a shared workflow while each remains useful.',profile:{title:'Workflow portrait',coverage:['The issued workflow sources'],unknowns:['Other modules have not been reviewed']},supports:ids.map(id=>({membershipId:id,claim:'Supports the described workflow constraint',context:'sample-project reviewed main checkout only'}))};
  return {job,plan:{operations:[op]}};
}
try {
  await g.init();
  const raw=await g.ingestTranscript('Raw host observation','raw-session','raw-id');
  assert.deepEqual(await g.ingestTranscript('Raw host observation','raw-session','raw-id'),raw);
  await assert.rejects(g.ingestTranscript('Changed raw content','raw-session','raw-id'),/idempotency_conflict/);
  const legacy=await g.createNode({dimension:'event',layer:'L0',content:'[user] Legacy observation',sessionId:'legacy-session',tags:['msgid:migrate_%']});
  assert.equal(await g.saveMessage('legacy-session','Legacy observation','user','migrate_%'),legacy.id);
  assert.notEqual(await g.saveMessage('another-session','Legacy observation','user','migrate_%'),legacy.id);
  const prefix='x'.repeat(250);
  assert.notEqual(await g.saveMessage('raw-session',prefix+'a','user'),await g.saveMessage('raw-session',prefix+'b','user'));
  const a=await create('routing'),b=await create('storage'),c=await create('validation'),d=await create('rendering');
  assert.deepEqual(await create('routing'),a);
  await assert.rejects(g.saveMemory('different payload',{idempotencyKey:'test-save-routing'}),/idempotency_conflict/);
  assert.equal((await g.getNodeById(a.id,{trackAccess:false}))!.sourceRefs![0].uri,ref('routing').uri);
  assert.equal((await g.getMemoryFreshness(member(a))).status,'unknown');
  for(const name of ['routing','storage','validation','rendering'])await g.observeSource({...ref(name),status:'present',expectedVersion:0});
  assert.equal((await g.getMemoryFreshness(member(a))).status,'checked');
  const unchanged=await g.observeSource({...ref('storage'),revision:'new-commit-same-file',status:'present',expectedVersion:1});
  assert.equal((await g.getMemoryFreshness(member(b))).status,'checked','same fingerprint remains checked across unrelated commits');
  assert.equal((await g.observeSource({...ref('storage'),revision:'new-commit-same-file',status:'present',expectedVersion:1})).version,unchanged.version);

  let offer=await synthesis([member(a),member(b)]);
  await assert.rejects(g.validateOrganizationPlan(offer.job.id,{operations:[{...offer.plan.operations[0],supports:[]}]}),/support claim/);
  await assert.rejects(g.commitOrganizationPlan(offer.job.id,{operations:[offer.plan.operations[0],{...offer.plan.operations[0],supports:[]}]}),/support claim/);
  assert.deepEqual((await g.getNodeById(a.id,{trackAccess:false}))!.profiles,[],'invalid whole plan cannot leave a partial profile');
  await g.validateOrganizationPlan(offer.job.id,offer.plan);
  const pReceipt=await g.commitOrganizationPlan(offer.job.id,offer.plan),p=pReceipt.createdMemoryIds[0],pm=(await g.getMemberships(p))[0].id;
  assert.deepEqual(await g.commitOrganizationPlan(offer.job.id,offer.plan),pReceipt);
  assert.equal((await g.getMemberships(a.id))[0].active,true);
  const view=await g.getProfile(pm,{limit:1});assert.equal(view.supports.length,1);assert.equal(view.nextOffset,1);assert.equal(view.freshness.status,'checked');
  assert.equal((await g.search({nodeId:p,...scope})).length,1,'support edges must not silently become ripple associations');
  assert.equal((await g.search({nodeId:p,...scope}))[0].node.profiles?.[0].membershipId,pm);
  offer=await synthesis([pm,member(c)]);const q=(await g.commitOrganizationPlan(offer.job.id,offer.plan)).createdMemoryIds[0],qm=(await g.getMemberships(q))[0].id;
  offer=await synthesis([member(c),member(d)]);const unrelated=(await g.commitOrganizationPlan(offer.job.id,offer.plan)).createdMemoryIds[0],um=(await g.getMemberships(unrelated))[0].id;
  assert((await g.getProfile(pm)).parents.includes(qm));
  const staleJob=await g.claimOrganizationJob({...scope,membershipIds:[member(a),member(b)]});assert(staleJob);
  const change=await g.observeSource({...ref('routing','r2'),status:'present',expectedVersion:1});
  assert(change.affectedProfileIds.includes(pm)&&change.affectedProfileIds.includes(qm));
  assert.equal((await g.getProfile(pm)).freshness.status,'needs_review');
  assert.equal((await g.getProfile(qm)).freshness.status,'needs_review');
  assert.equal((await g.getProfile(um)).freshness.status,'checked');
  await assert.rejects(g.commitOrganizationPlan(staleJob.id,{operations:[{kind:'keep',membershipIds:[member(a)]}]}),/stale_snapshot/);
  await g.releaseOrganizationJob(staleJob.id);
  await assert.rejects(g.observeSource({...ref('routing','r3'),status:'present',expectedVersion:1}),/stale_observation/);
  await g.observeSource({...ref('routing','feature','feature-branch'),status:'present',expectedVersion:0});
  assert.equal((await g.getSourceObservation(ref('routing').uri,'main')).revision,'r2');
  assert.equal((await g.getProfile(um,{sourceContext:'feature-branch'})).freshness.status,'unknown');
  const oldA=(await g.getNodeById(a.id,{trackAccess:false}))!;
  await assert.rejects(g.editMemory(a.id,{sourceRefs:[ref('routing','r2')]}),/expectedUpdatedAt/);
  await g.editMemory(a.id,{sourceRefs:[ref('routing','r2')],expectedUpdatedAt:oldA.updatedAt,content:oldA.content+' Rechecked against r2.'});
  assert.equal((await g.getProfile(pm)).freshness.status,'needs_review','updating sources alone cannot validate a derived profile');
  offer=await synthesis([member(a),member(b)],pm);const updated=await g.commitOrganizationPlan(offer.job.id,offer.plan);assert.deepEqual(updated.updatedMemoryIds,[p]);
  assert.equal((await g.getProfile(pm)).freshness.status,'checked');assert.equal((await g.getProfile(qm)).freshness.status,'needs_review');
  assert.equal((await g.getProfileHistory(pm)).length,2);
  offer=await synthesis([pm,member(c)],qm);await g.commitOrganizationPlan(offer.job.id,offer.plan);
  assert.equal((await g.getProfile(qm)).freshness.status,'checked');
  offer=await synthesis([qm,member(c)],pm);await assert.rejects(g.validateOrganizationPlan(offer.job.id,offer.plan),/cycle/);await g.releaseOrganizationJob(offer.job.id);
  const foreign=await g.addMembership(a.id,'sample-project/teaching',scope.memoryType);
  await assert.rejects(g.claimOrganizationJob({...scope,membershipIds:[foreign.id,member(b)]}),/outside this space/);
  const cp={hostId:'sample-agent',runId:'review-run',checkpointId:'end',...scope,outcome:'saved' as const,reason:'Explicit code observations saved',memoryIds:[a.id,b.id]};
  const receipt=await g.checkpoint(cp);assert(receipt.workId);assert.deepEqual(await g.checkpoint(cp),receipt);
  await assert.rejects(g.checkpoint({...cp,reason:'different'}),/idempotency_conflict/);
  assert.equal((await g.checkpoint({...cp,checkpointId:'noop',outcome:'no_change',memoryIds:[]})).workId,null);
  other=new GraphMemory();await other.init();
  const sameMessage=await Promise.all([g.saveMessage('shared-session','Concurrent host capture','assistant','shared-message'),other.saveMessage('shared-session','Concurrent host capture','assistant','shared-message')]);
  assert.equal(sameMessage[0],sameMessage[1]);
  await assert.rejects(g.saveMessage('shared-session','Different payload','assistant','shared-message'),/idempotency_conflict/);

  const claims=await Promise.all([g.claimHostWork(scope.spaceId,scope.memoryType),other.claimHostWork(scope.spaceId,scope.memoryType)]);
  assert.equal(claims.filter(Boolean).length,1);
  const work=claims.find(Boolean)!;
  await assert.rejects(g.finishHostWork({workId:work.id,leaseToken:'wrong',outcome:'no_change',reason:'No changes'}),/stale_work_lease/);
  await assert.rejects(g.finishHostWork({workId:work.id,leaseToken:work.leaseToken,outcome:'completed',reason:'Done'}),/requires a completed/);
  const done={workId:work.id,leaseToken:work.leaseToken,outcome:'no_change' as const,reason:'Profiles already organized in earlier committed jobs'};
  await g.finishHostWork(done);assert.deepEqual(await g.finishHostWork(done),{status:'completed'});
  assert(!(JSON.stringify(await g.listHostWork(scope.spaceId,scope.memoryType))).includes(work.leaseToken));
  const retryCP=await g.checkpoint({...cp,checkpointId:'lease-recovery'});
  const firstLease=await g.claimHostWork(scope.spaceId,scope.memoryType);assert(firstLease);
  const sql=await open({filename:process.env.MEMORY_DB_PATH!,driver:sqlite3.Database});
  try {
    await sql.run('UPDATE host_work SET lease_until=0 WHERE id=?',[retryCP.workId]);
    await assert.rejects(g.renewHostWork(firstLease.id,firstLease.leaseToken),/stale_work_lease/);
    const recovered=await other.claimHostWork(scope.spaceId,scope.memoryType);assert(recovered);assert.notEqual(recovered.leaseToken,firstLease.leaseToken);
    await assert.rejects(g.finishHostWork({...done,workId:firstLease.id,leaseToken:firstLease.leaseToken}),/stale_work_lease/);
    await sql.run('UPDATE host_work SET lease_until=0,attempts=5 WHERE id=?',[recovered.id]);
    assert.equal(await g.claimHostWork(scope.spaceId,scope.memoryType),null);
    assert.equal((await g.listHostWork(scope.spaceId,scope.memoryType)).find(w=>w.id===recovered.id).status,'failed');
    await g.retryHostWork(recovered.id,'Fixture verified retry cause');
    const retried=await g.claimHostWork(scope.spaceId,scope.memoryType);assert.equal(retried!.attempts,1);
    await g.finishHostWork({...done,workId:retried!.id,leaseToken:retried!.leaseToken});
    assert.equal((await sql.get('SELECT COUNT(*) AS n FROM memory_job_sources WHERE node_id=?',[sameMessage[0]])).n,1);
    assert.equal((await sql.get('SELECT COUNT(*) AS n FROM memory_job_sources WHERE node_id=?',[legacy.id])).n,1);
  } finally {await sql.close();}
  await other.close();other=undefined;await g.close();g=new GraphMemory();await g.init();
  assert.deepEqual(await g.ingestTranscript('Raw host observation','raw-session','raw-id'),raw);
  assert.equal(await g.saveMessage('shared-session','Concurrent host capture','assistant','shared-message'),sameMessage[0]);
  assert.deepEqual(await g.checkpoint(cp),receipt);assert.equal((await g.getProfile(pm)).revision,2);
  assert.deepEqual(await create('routing'),a,'save receipt survives restart even after later source edit');
  await g.addMembership(p,'another-space',scope.memoryType);
  offer=await synthesis([member(a),member(b)],pm);await assert.rejects(g.validateOrganizationPlan(offer.job.id,offer.plan),/Shared profile body/);await g.releaseOrganizationJob(offer.job.id);
  const job=await g.claimOrganizationJob({...scope,membershipIds:[member(a),member(b)]});assert(job);
  await g.commitOrganizationPlan(job.id,{operations:[{kind:'consolidate',membershipIds:[member(a),member(b)],content:'Combined detail retaining both workflow constraints.'}]});
  assert.equal((await g.getProfile(pm)).freshness.status,'needs_review');
  assert.equal((await g.getMemberships(a.id)).find(m=>m.id===foreign.id)?.active,true);
  await g.deleteNode(c.id,'test deletion');assert.equal((await g.getProfile(qm)).freshness.status,'needs_review');
  assert(capabilities().hostPolicy.includes('no_change'));assert(hostOperations(g).some(op=>op.name==='memory_organization_candidates'));
  console.log('PASS: non-destructive profiles, DAG/visibility boundaries, scoped versions, source changes, immutable revisions, idempotent saves/checkpoints, leased cross-process host work and restart recovery');
} finally {await other?.close();await g.close();await fs.rm(dir,{recursive:true,force:true});}
